params/imu: { 
mag_offset_x: 50.44, mag_offset_y: 97.58, mag_offset_z: 33.00,
mag_soft_iron_ix: 0.993, mag_soft_iron_iy: -0.020, mag_soft_iron_iz: -0.024,
mag_soft_iron_jx: -0.020, mag_soft_iron_jy: 0.987, mag_soft_iron_jz: 0.007,
mag_soft_iron_kx: -0.024, mag_soft_iron_ky: 0.007, mag_soft_iron_kz: 1.021,
sensor_read_rate: 400, output_rate_divider: 8,
adaptive_gain: 1, bias_estimation: 1,
gain_acc: 0.02, gain_mag: 0.01, bias_alpha: 0.25,
kAngularVelocityThreshold: 0.055, kAccelerationThreshold: 0.19, kDeltaAngularVelocityThreshold: 0.033,
imu_frame_id: "base_imu_link", mag_frame_id: "base_imu_link",
gfsr: 2, afsr: 1,
calibration_mode: 0,
steady_limit: 32,
world_frame: 0
}
