params/imu: { 
mag_offset_x: 51.00, mag_offset_y: 98.60, mag_offset_z: 31.11, 
mag_soft_iron_ix: 0.990, mag_soft_iron_iy: -0.025, mag_soft_iron_iz: -0.016, 
mag_soft_iron_jx: -0.025, mag_soft_iron_jy: 0.996, mag_soft_iron_jz: 0.011, 
mag_soft_iron_kx: -0.016, mag_soft_iron_ky: 0.011, mag_soft_iron_kz: 1.015, 
sensor_read_rate: 400, output_rate_divider: 8,
adaptive_gain: 1, bias_estimation: 1,
gain_acc: 0.02, gain_mag: 0.01, bias_alpha: 0.4,
kAngularVelocityThreshold: 0.2, kAccelerationThreshold: 0.4, kDeltaAngularVelocityThreshold: 0.05,
imu_frame_id: "base_imu_link", mag_frame_id: "mag_imu_link",
gfsr: 2, afsr: 1,
calibration_mode: 0
}
